/**
 * 默认的搜索引擎列表（统一结构）
 */
export const DEFAULT_ENGINES = [
  {
    id: 'google',
    name: 'Google',
    url: 'https://www.google.com/search?q=%s',
    badge: 'G',
    domain: 'google.com',
    param: 'q',
    isTarget: true,
    isSource: true,
  },
  {
    id: 'baidu',
    name: '百度',
    url: 'https://www.baidu.com/s?wd=%s',
    badge: '百度',
    domain: 'baidu.com',
    param: 'wd,word',
    isTarget: true,
    isSource: true,
  },
  {
    id: 'bing',
    name: 'Bing',
    url: 'https://www.bing.com/search?q=%s',
    badge: 'Bing',
    domain: 'bing.com',
    param: 'q',
    isTarget: true,
    isSource: true,
  },
  {
    id: 'bing_cn',
    name: 'Bing 中国',
    url: 'https://cn.bing.com/search?q=%s',
    badge: '必应',
    domain: 'cn.bing.com',
    param: 'q',
    isTarget: false,
    isSource: true,
  },
  {
    id: 'duckduckgo',
    name: 'DuckDuckGo',
    url: 'https://duckduckgo.com/?q=%s',
    badge: 'D',
    domain: 'duckduckgo.com',
    param: 'q',
    isTarget: true,
    isSource: true,
  },
  {
    id: 'sogou',
    name: '搜狗',
    url: 'https://www.sogou.com/web?query=%s',
    badge: '搜狗',
    domain: 'sogou.com',
    param: 'query',
    isTarget: false,
    isSource: true,
  },
  {
    id: '360so',
    name: '360搜索',
    url: 'https://www.so.com/s?q=%s',
    badge: '360',
    domain: 'so.com',
    param: 'q',
    isTarget: false,
    isSource: true,
  },
  {
    id: 'yandex',
    name: 'Yandex',
    url: 'https://yandex.com/search/?text=%s',
    badge: 'Y',
    domain: 'yandex.com',
    param: 'text',
    isTarget: false,
    isSource: true,
  },
  {
    id: 'yahoo',
    name: 'Yahoo',
    url: 'https://search.yahoo.com/search?p=%s',
    badge: 'Y!',
    domain: 'search.yahoo.com',
    param: 'p',
    isTarget: false,
    isSource: true,
  },
  {
    id: 'bilibili',
    name: 'Bilibili',
    url: 'https://search.bilibili.com/all?keyword=%s',
    badge: 'B站',
    domain: 'search.bilibili.com',
    param: 'keyword',
    isTarget: false,
    isSource: true,
  },
  {
    id: 'github',
    name: 'GitHub',
    url: 'https://github.com/search?q=%s',
    badge: 'GH',
    domain: 'github.com',
    param: 'q',
    isTarget: false,
    isSource: true,
  },
  {
    id: 'google_translate',
    name: 'Google Translate',
    url: 'https://translate.google.com/?sl=auto&text=%s&op=translate',
    badge: 'GT',
    domain: 'translate.google.com',
    param: 'text',
    isTarget: false,
    isSource: true,
  },
  {
    id: 'baidu_translate',
    name: '百度翻译',
    url: 'https://fanyi.baidu.com/#auto/zh/%s',
    badge: '翻译',
    domain: 'fanyi.baidu.com',
    param: 'text',
    isTarget: false,
    isSource: true,
  },
]
